### PR TITLE
This PR includes basic UI widgets

### PR DESCRIPTION
**Pull request by Nirmitjatana**
# Pull Request Type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

# Purpose
- To keep tabs on the progress

# Does this PR introduce any new bug?
- [ ] Yes
- [x] No
- [ ] Maybe

#### Issue Reference: [https://github.com/GDGVIT/cadence-app/issues/3](url)

# Other information

# Did you learn something new?
- Working with flutter and dart

### CODE REVIEW

**Comment by Nirmitjatana** [comment]
@BRO3886 This PR is to keep tabs on progress with Spotify API and integration.

- I have started making the UI and widgets
- figured all the web API class to fetch playlist/ top tracks of the user
- figured how to play songs in the app

Up next:
- Will integrate the web API calls in App.

**Comment by Nirmitjatana** [comment]
@BRO3886 how to fix these linting issues with Dart and Kotlin?

**Comment by BRO3886** [comment]
> @BRO3886 how to fix these linting issues with Dart and Kotlin?

I checked the lint log, it's mostly because the formatter was trying to find flutter's URI and throwing errors because it does not exist. You can leave it for a while, or write a custom action that uses `subosito/flutter-action`, then run `flutter analyze` and `flutter format` to check code.

**Comment by BRO3886** [comment]
@Nirmitjatana also please edit the PR with a relevant title and add [WIP] so I know I don't need to merge yet

**Comment by Nirmitjatana** [comment]
@BRO3886 You can merge this PR now

**Comment by BRO3886** [comment]
@Nirmitjatana I think we should disable linting for you because of obvious problems with linting and then merge? You can do so by editing `.github/workflows/linter.yml` 
```yaml
VALIDATE_ALL_CODEBASE:  ̶t̶r̶u̶e̶  ➔ false
```
**UPDATE**:
Let's not disable, try adding this before linter runs
```yaml
 - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get packages in a Flutter project
        run: flutter pub get
      - name: Run lint
      .
      .
      .
```

**Comment by Nirmitjatana** [comment]
@BRO3886 worked like a charm!

**Comment by BRO3886** [comment]
LGTM, merging

**Pull request merged**
